up

diff --git a/.github/workflows/lint2.yaml b/.github/workflows/lint2.yaml
--- a/.github/workflows/lint2.yaml
+++ b/.github/workflows/lint2.yaml
@@ -95,6 +95,8 @@ jobs:
   tflint:
     # if: ${{ (!contains(fromJSON(inputs.skip), github.job)) }}
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
     steps:
     - name: Checkout
       uses: actions/checkout@v3
@@ -115,9 +117,21 @@ jobs:
 
     - name: Init TFLint
       run: tflint --init
-      # env:
-      #   # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
-      #   GITHUB_TOKEN: ${{ github.token }}
 
     - name: Run TFLint
-      run: tflint --recursive
+      shell: bash
+      run: |
+        tflint --recursive --format=sarif > tflint.sarif
+
+    - name: Show result TFLint
+      shell: bash
+      if: (( success() || failure() ) )
+      run: |
+        cat tflint.sarif 
+
+    - name: Upload terrascan SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+      if: ( !env.ACT && ( success() || failure() ) )
+      # if: (( success() || failure() ) )
+      with:
+        sarif_file: tflint.sarif
