test

diff --git a/.github/workflows/lint2.yaml b/.github/workflows/lint2.yaml
--- a/.github/workflows/lint2.yaml
+++ b/.github/workflows/lint2.yaml
@@ -11,84 +11,126 @@ on:
           default: "1.28.1"
   
 jobs:
-  # checkov:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
-  #   - name: Test with Checkov
-  #     id: checkov
-  #     uses: bridgecrewio/checkov-action@v12.1346.0
-  #     with:
-  #       framework: terraform
-  #       output_format: sarif
-  #       output_file_path: sarif_dir
-  #       version: ${{ inputs.checkov_version }}
-  #   - name: Upload terrascan SARIF file
-  #     uses: github/codeql-action/upload-sarif@v2
-  #     if: success() || failure()
-  #     with:
-  #       sarif_file: sarif_dir/results_sarif.sarif
-
-  # tfsec:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v3
-  #   - name: tfsec
-  #     uses: aquasecurity/tfsec-sarif-action@v0.1.4
-  #     with:
-  #       tfsec_version: ${{ inputs.tfsec_version }}
-  #       sarif_file: tfsec.sarif
-  #   - name: Upload terrascan SARIF file
-  #     uses: github/codeql-action/upload-sarif@v2
-  #     if: success() || failure()
-  #     with:
-  #       sarif_file: tfsec.sarif
-      
-  find-test-dirs:      
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout
-          uses: actions/checkout@v3
-        - name: Find test directories
-          shell: bash
-          run: |
-            ls -R
-            find "modules" -name "tests"
-        - id: set-dirs
-          run: |
-            dirs=$(find ./ -name "test" -or -name "tests" \
-              -not -path '*/.terraform/*' \
-              | jq --raw-input --slurp 'split("\n")[:-1]')
-            echo "dirs=$(echo $dirs)" >> $GITHUB_OUTPUT
-      outputs:
-        dirs: ${{ steps.set-dirs.outputs.dirs }}
-
-  test:
+  checkov:
+    # if: ${{ (!contains(fromJSON(inputs.skip), github.job)) }}
     runs-on: ubuntu-latest
-    needs: find-test-dirs
-    strategy:
-        matrix:
-          dirs: ${{fromJson(needs.find-test-dirs.outputs.dirs)}}
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Python 3.11
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.11"
-      - name: Install dependencies
-        working-directory: ${{ matrix.dirs }}
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-      - name: Test with pytest
-        working-directory: ${{ matrix.dirs }}
-        run: |
-          pytest
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Test with Checkov
+      id: checkov
+      uses: bridgecrewio/checkov-action@master #v12.1346.0
+      with:
+        # directory: .
+        framework: terraform
+        # soft_fail: true
+        output_format: sarif
+        output_file_path: sarif_dir
+        # version: 2.3.245
+        # 2.0.929
+    - name: Upload terrascan SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+      if: success() || failure()
+      with:
+        sarif_file: sarif_dir/results_sarif.sarif
 
+  tfsec:
+    # if: ${{ (!contains(fromJSON(inputs.skip), github.job)) }}
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: tfsec
+      uses: aquasecurity/tfsec-sarif-action@v0.1.4
+      with:
+        tfsec_version: latest
+        sarif_file: tfsec.sarif
+    - run: cat tfsec.sarif
+      shell: bash
+    - name: Upload terrascan SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+      with:
+        sarif_file: tfsec.sarif
 
+  terrascan:
+    # if: ${{ (!contains(fromJSON(inputs.skip), github.job)) }}
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: terrascan
+      uses: tenable/terrascan-action@main
+      with:
+        iac_type: 'terraform'
+        iac_version: 'v14'
+        policy_type: 'aws'
+        sarif_upload: true
+        # only_warn: true
+    - name: Upload terrascan SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+      if: ( !env.ACT && ( success() || failure() ) )
+      with:
+        sarif_file: terrascan.sarif
 
+  regula:
+    # if: ${{ (!contains(fromJSON(inputs.skip), github.job)) }}
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Regula Terraform
+      uses: fugue/regula-action@v3.2.1
+  
+  # tflint:
+  #   # if: ${{ (!contains(fromJSON(inputs.skip), github.job)) }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #   - name: Lint Code Base
+  #     uses: github/super-linter@v5
+      # env:
+      #   DEFAULT_BRANCH: master
+  tflint:
+    # if: ${{ (!contains(fromJSON(inputs.skip), github.job)) }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
 
+    - uses: actions/cache@v3
+      name: Cache plugin dir
+      with:
+        path: ~/.tflint.d/plugins
+        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
 
+    - uses: terraform-linters/setup-tflint@v3
+      name: Setup TFLint
+      with:
+        tflint_version: v0.44.1
 
+    - name: Show version
+      run: tflint --version
+
+    - name: Init TFLint
+      run: tflint --init
+
+    - name: Run TFLint
+      shell: bash
+      run: |
+        tflint --recursive --format=sarif > tflint.sarif
+
+    - name: Show result TFLint
+      shell: bash
+      if: (( success() || failure() ) )
+      run: |
+        cat tflint.sarif 
+
+    - name: Upload terrascan SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+      if: ( !env.ACT && ( success() || failure() ) )
+      # if: (( success() || failure() ) )
+      with:
+        sarif_file: tflint.sarif
