2

diff --git a/.github/workflows/lint2.yaml b/.github/workflows/lint2.yaml
--- a/.github/workflows/lint2.yaml
+++ b/.github/workflows/lint2.yaml
@@ -11,37 +11,73 @@ on:
           default: "1.28.1"
   
 jobs:
-  checkov:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Test with Checkov
-      id: checkov
-      uses: bridgecrewio/checkov-action@v12.1346.0
-      with:
-        framework: terraform
-        output_format: sarif
-        output_file_path: sarif_dir
-        version: ${{ inputs.checkov_version }}
-    - name: Upload terrascan SARIF file
-      uses: github/codeql-action/upload-sarif@v2
-      if: success() || failure()
-      with:
-        sarif_file: sarif_dir/results_sarif.sarif
+  # checkov:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #   - name: Test with Checkov
+  #     id: checkov
+  #     uses: bridgecrewio/checkov-action@v12.1346.0
+  #     with:
+  #       framework: terraform
+  #       output_format: sarif
+  #       output_file_path: sarif_dir
+  #       version: ${{ inputs.checkov_version }}
+  #   - name: Upload terrascan SARIF file
+  #     uses: github/codeql-action/upload-sarif@v2
+  #     if: success() || failure()
+  #     with:
+  #       sarif_file: sarif_dir/results_sarif.sarif
 
-  tfsec:
+  # tfsec:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #   - name: tfsec
+  #     uses: aquasecurity/tfsec-sarif-action@v0.1.4
+  #     with:
+  #       tfsec_version: ${{ inputs.tfsec_version }}
+  #       sarif_file: tfsec.sarif
+  #   - name: Upload terrascan SARIF file
+  #     uses: github/codeql-action/upload-sarif@v2
+  #     if: success() || failure()
+  #     with:
+  #       sarif_file: tfsec.sarif
+      
+  find-test-dirs:      
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout
+          uses: actions/checkout@v3
+        - name: Find test directories
+          shell: bash
+          run: |
+            ls -R
+            find "modules" -name "tests"
+        - id: set-dirs
+          run: |
+            dirs=$(find ./ -name 'tests' -o -name 'test' \
+              -not -path '*/.terraform/*')
+            echo "dirs=$(echo $dirs)" >> $GITHUB_OUTPUT
+      outputs:
+        dirs: ${{ steps.set-dirs.outputs.dirs }}
+    
+
+  test:
     runs-on: ubuntu-latest
+    needs: find-test-dirs
+    strategy:
+        matrix:
+          dirs: ${{needs.find-test-dirs.outputs.dirs}}
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: tfsec
-      uses: aquasecurity/tfsec-sarif-action@v0.1.4
-      with:
-        tfsec_version: ${{ inputs.tfsec_version }}
-        sarif_file: tfsec.sarif
-    - name: Upload terrascan SARIF file
-      uses: github/codeql-action/upload-sarif@v2
-      if: success() || failure()
-      with:
-        sarif_file: tfsec.sarif
+        - name: a
+          run: echo "${{ matrix.dirs }} xxxxx"
+  #   matrix
+
+
+
+
+
+
